console.log("04장 변수 실험");
console.log("");
console.log("정상 실행 실험:");
console.log("- node 04-variables/reassignment.js");
console.log("- node 04-variables/primitive-vs-object.js");
console.log("");
console.log("에러 관찰 실험:");
console.log("- node 04-variables/const-reassignment-error.js");
console.log("- node 04-variables/const-declaration-error.js");
console.log("- node 04-variables/reference-error.js");
